name: My Backend Deployment 

on:
    push:
        branches:
        - main
        paths:
        - 'backend/**'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout the code'
          uses: actions/checkout@v2
           
        - name: 'Zip Lambda Function'
          run: |
            zip -r lambda_function.zip lambda_function.py
            

        - name: 'Configure AWS credentials'   
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
            
        - name: 'Upload zipfile to S3'
          run: |
            aws s3 cp lambda_function.zip s3://${{ secrets.AWS_S3_BUCKET }}/

        - name: 'Update Source Code'
          run: |
            aws lambda update-function-code --function-name ${{secrets.AWS_LAMBDA_NAME}} \
            --s3-bucket ${{secrets.AWS_S3_BUCKET}} --s3-key ${{secrets.AWS_S3_KEY}} \
            --region ${{secrets.AWS_REGION}} 