name: My Backend Deployment 

on:
    push:
        branches:
        - main
        paths:
        - 'backend/**'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout the code'
          uses: actions/checkout@v2
           
        - name: 'Zip Lambda Function'
          run: zip get_vistor_counter.zip lambda_function.py

        - name: 'Upload zipfile to S3'
          uses: shallwefootball/s3-upload-action@master
          with:
            aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
            aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
            source_dir: '../backend/api/get_visitor_counter.zip'

        - name: 'Configure AWS credentials'   
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
            
        - name: 'Update Source Code'
          run: |
            aws lambda update-function-code --function-name ${{secrets.AWS_LAMBDA_NAME}} \
            --s3-bucket ${{secrets.AWS_S3_BUCKET}} --s3-key ${{secrets.AWS_S3_KEY}} \
            --region ${{secrets.AWS_REGION}} 