name: My frontend deployment

on:
    push:
        branches:
        - main
        paths:
        - 'frontend/**'


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: shallwefootball/s3-upload-action@master
          with:
            aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
            aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
            source_dir: 'frontend'
                 


             